anxillawebapp/__init__.py
from flask import Flask
from anxillawebapp.config import Config

def create_app(config_Class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    from anxillawebapp.main.routes import main

    app.register_blueprint(main)

    return app

anxillawebapp/main/routes.py
from email import message
from pickle import TRUE
from flask import Flask, render_template, url_for, redirect, request, Blueprint, app, session, flash


main = Blueprint('main', __name__)

@main.route("/", methods = ['GET','POST'])
def index():
    if request.method == 'POST':
        username=request.form['username']
        password=request.form['password']
        if username == 'admin' and password== 'admin@123':
            session['user'] = True
            return redirect(url_for('main.upgrade'))
        else:
            return render_template('public_pages/index.html', message= str("your login credential are invalid"))
    else:
        session['user'] = False
        return render_template('public_pages/index.html')

@main.route("/upgrade", methods = ['GET', 'POST'])
def upgrade():
    if session.get("user") == True:
        return render_template('public_pages/upgrade.html')
    else:
        return redirect(url_for('main.index'))

@main.route("/review", methods = ['GET', 'POST'])
def review():
    if session.get("user") == True:
        return render_template('public_pages/review.html')
    else:
        return redirect(url_for('main.index'))

@main.route("/payment", methods = ['GET', 'POST'])
def payment():
    if session.get("user") == True:
        return render_template('public_pages/payment.html')
    else:
        return redirect(url_for('main.index'))


@main.route("/confirmation", methods = ['GET', 'POST'])
def confirmation():
    if session.get("user") == True:
        return render_template('public_pages/confirmation.html')
    else:
        return redirect(url_for('main.index'))

anxillawebapp/templates/public_assets.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ancillary</title>
    <!-- Bootstrap CSS Link -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!-- Bootstrap Icons -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"
    />
    <link rel="stylesheet" href="https://use.fontawesome.com/a34asdfsd.js" />
    <!-- Custom CSS Link -->
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/customStyles.css')}}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/colors.css')}}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/responsive.css')}}" />

    <!-- SVG Gauge CSS Link-->
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/svgGauge.css')}}" />
  </head>

  <body>
    {% block content %}{% endblock %}



    <!-- Bootstrap JS Link -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://kit.fontawesome.com/0953a6ce7b.js"
      crossorigin="anonymous"
    ></script>

    <!-- Custom JS Link-->
    <script src="{{ url_for('static', filename='assets/js/script.js')}}"></script>
    <script src="{{ url_for('static', filename='assets/js/svgGauge.js')}}"></script>
    <script>
      let loginMsg = document.querySelector(".loginMsg");
      setTimeout(function(){
        loginMsg.style.display = "none";
      }, 3000);
    </script>
  </body>
</html>

anxillawebapp/templates/public_pages/confirmation.html
{% extends "public_assets.html" %}
{% block content %}


<div class="container p-4">
    <div class="logo_container">
        <img class="img-fluid logo" src="{{ url_for('static', filename='assets/images/logo.png')}}" alt="">
    </div>
    <div class="confirm_bg my-4">
        <img class="img-fluid w-100" src="{{ url_for('static', filename='assets/images/confirm-bg.png')}}" alt="">
    </div>
    <div class="confirm-text">
        <p class="my-4" style="font-weight: 600; font-size: 18px; color: #095fac;">Dear Robert,</p>
        <p>Thank you for using upgrade travel option. Your confirmation ID is #1238123</p>
        <p>Please note that the upgrade price will be charge only if you are upgraded to your selected ancillary.</p>
        <p class="mt-4" style="font-weight: 600; font-size: 18px; color: #042e5f;">Regards,</p>
        <p style="font-weight: 600; font-size: 18px; color: #042e5f;">Anxilla</p>
    </div>
    <div class="proceedPaymentContainer d-flex justify-content-center">
        <a href="{{ url_for('main.upgrade')}}">
            <div class="proceedPaymentBtn bgType9 text-center px-3 py-2 mt-4">
               Go Home
            </div>
        </a>
    </div>
</div>


{% endblock content %}

anxillawebapp/templates/public_pages/index.html
{% extends "public_assets.html" %}
{% block content %}
      <main class="container">
          <nav class="navbar row my-3">
              <div class="col-lg-4">
                <img class="img-fluid logo" src="{{ url_for('static', filename='assets/images/logo.png')}}" alt="">
              </div>
              <div class="col-lg-8">
                  <ul>
                      <li class="colorType1">Deals</li>
                      <li class="colorType1">Plan Your Trip</li>
                      <li class="colorType1">Experience</li>
                      <li class="colorType1">Destinations</li>
                      <li class="colorType1" id="enrich">Enrich</li>
                      <li class="colorType1">AskMH</li>
                      <li class="colorType1"><img class="img-fluid en" src="{{ url_for('static', filename='assets/images/en.png')}}" alt=""> EN</li>
                      <li class="colorType1"><i class="bi bi-search colorType1 font-weight-bold" id="searchIcon"></i></li>
                  </ul>
              </div>
          </nav>
          <div class="menuContainer row colorType3">
            <div class="col-lg-8">
                <ul>
                    <li class="menuList">Flights</li>
                    <li class="menuList">Flight + Home</li>
                    <li class="menuList">Manage</li>
                    <li class="menuList">Check-in</li>
                    <li class="menuList">Flight Status</li>
                    <li class="menuList">Upgrade Travel Option</li>
                </ul>
            </div>
            <!-- <div class="col-lg-4">
                <button class="loginBtn">Log In/Sign Up</button>
            </div> -->
          </div>
          <div class="login_page">
              <h1>Login</h1>
              <hr>
             
              <form action="" method="POST" id="login_form">
                  <div class="text_box">
                  <i class="fa fa-user" aria-hidden="true"></i>   
                  <label for="uname">USERNAME</label>
                  <input type="text" id="username" name="username"><br>
                  </div>
                  <div class="text_box">
                  <i class="fa fa-lock" aria-hidden="true"></i> 
                  <label for="password">PASSWORD</label>
                  <input type="password" id="password" name="password"><br>
                  </div>
                  {% if message %}
                  <p class="loginMsg">{{ message }}</p>
                  
                  {% endif %}
                  <div class="d-flex justify-content-center">
                    <div class="btn">
                        <input id="loginBtn" type="submit"  value="login">
                        </div>
                  </div>
              </form>
              </div>
          </div>
      </main>

      


   

      {% endblock content %}

anxillawebapp/templates/public_pages/payment.html
{% extends "public_assets.html" %}
{% block content %}
    <main class="container">
        <header class="row heading">
            <div class="col-lg-8">
                <img class="img-fluid logo" src="{{ url_for('static', filename='assets/images/logo.png')}}" alt="" />
            </div>
            <div class="col-lg-4 d-flex align-items-center justify-content-between">
                <div class="bookingReference">
                    <a href="{{ url_for('main.index')}}">Go to Booking reference</a>
                </div>
                <div class="userDetails">
                    <p class="userName">Hello Robert!</p>
                    <i class="bi bi-person userIcon colorType2"></i>
                </div>
            </div>
        </header>

        <div class="stepsHeader bgType3">
            <ul class="text-center">
                <li>Three Steps to upgrade</li>
                <li><a href="{{ url_for('main.upgrade')}}"><span id="checkedSpan"><i class="fa fa-check" id="stepHeaderCheckIcon"></i></span>Select Upgrade</a>
                </li>
                <li><a href="{{ url_for('main.review')}}"><span id="checkedSpan"><i class="fa fa-check" id="stepHeaderCheckIcon"></i></span>Review and Submit</a>
                </li>
                <li class="stepsHeaderActive"><span>3</span>Payment Information</li>
            </ul>
        </div>

        <section class="sectionContainer bgType1">
            <div class="row">
                <div class="paymentContainer col-9 my-2 py-3">
                    <div class="paymentHeading">
                        <h3>Select the payment method</h3>
                        <p class="colorType4">All transactions are secured and encrypted. Credit card information is
                            never stored.</p>
                    </div>

                    <div class="paymentMethodContainer bgType6 my-3 ">
                        <div class="paypalContainer">
                            <input type="radio" name="payment" />
                            <img class="paypalLogo img-fluid" src="{{ url_for('static', filename='assets/images/paypal.png')}}" alt="">
                        </div>
                        <div class="paypalContainer d-flex justify-content-between align-items-center"
                            style="border: none;">
                            <div class="creditCardOption d-flex align-items-center">
                                <input type="radio" name="payment" style="top: 0;" />
                                <p>Credit Card / Debit Card</p>
                            </div>
                            <div class="creditCardImages">
                                <img class="cardLogo img-fluid" src="{{ url_for('static', filename='assets/images/maestro.svg')}}" alt="">
                                <img class="cardLogo img-fluid" src="{{ url_for('static', filename='assets/images/visa.png')}}" alt="">
                                <img class="cardLogo img-fluid" src="{{ url_for('static', filename='assets/images/americanexpress.jpg')}}" alt="">
                                <img class="cardLogo img-fluid" src="{{ url_for('static', filename='assets/images/discover.png')}}" alt="">
                            </div>
                        </div>
                        <div class="cardLayoutContainer d-flex justify-content-center my-4">
                            <img class="img-fluid" src="{{ url_for('static', filename='assets/images/cardlayout.png')}}" alt="">
                        </div>
                        <div class="cardDetailsContainer">
                            <div class="row">
                                <div class="col-3"></div>
                                <div class="cardNumberContainer col-6">
                                    <p class="colorType4 my-1">Card Number</p>
                                    <div class="cardNumber d-flex justify-content-start align-items-center">
                                        <div class="cardIcon mx-1">
                                            <i class="far fa-credit-card colorType6"></i>
                                        </div>
                                        <div class="cardNumberHide mx-2 colorType6">
                                            <i class="fas fa-asterisk"></i>
                                            <i class="fas fa-asterisk"></i>
                                            <i class="fas fa-asterisk"></i>
                                            <i class="fas fa-asterisk"></i>
                                        </div>
                                        <div class="cardNumberHide mx-2 colorType6">
                                            <i class="fas fa-asterisk"></i>
                                            <i class="fas fa-asterisk"></i>
                                            <i class="fas fa-asterisk"></i>
                                            <i class="fas fa-asterisk"></i>
                                        </div>
                                        <div class="cardNumberHide mx-2 colorType6">
                                            <i class="fas fa-asterisk"></i>
                                            <i class="fas fa-asterisk"></i>
                                            <i class="fas fa-asterisk"></i>
                                            <i class="fas fa-asterisk"></i>
                                        </div>
                                        <div class="cardNumberHide mx-2 colorType6">
                                            <i class="fas fa-asterisk"></i>
                                            <i class="fas fa-asterisk"></i>
                                            <i class="fas fa-asterisk"></i>
                                            <i class="fas fa-asterisk"></i>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-3"></div>
                            </div>
                        </div>
                        <div class="cardDetailsContainer my-4 ">
                            <div class="row">
                                <div class="col-3"></div>
                                <div class="cardNumberContainer col-6">
                                    <div class="row">
                                        <div class="col-8">
                                            <p class="colorType4 my-1">Card Holder</p>
                                            <div class="cardNumber" style="border: 1px solid #015aaa;">
                                                Robert Downey
                                            </div>
                                        </div>
                                        <div class="col-2">
                                            <p class="colorType4 my-1">Exp Date</p>
                                            <div class="cardNumber text-center colorType6">
                                                12/22
                                            </div>
                                        </div>
                                        <div class="col-2">
                                            <p class="colorType4 my-1">CVC</p>
                                            <div class="cardNumber text-center colorType6">
                                                * * *
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-3"></div>
                            </div>
                        </div>
                        <div class="row" style="margin-top: 4rem;">
                            <div class="col-5"></div>
                            <div class="col-2">
                                <div class="proceedPaymentContainer">
                                    <a href="{{ url_for('main.confirmation')}}">
                                        <div class="proceedPaymentBtn bgType9 text-center px-3 py-2">
                                           Pay
                                        </div>
                                    </a>
                                </div>
                            </div>
                            <div class="col-5"></div>
                        </div>
                    </div>
                </div>
                <div class="col-3">

                </div>

            </div>

        </section>
        {% endblock content %}